home/urls.py
# home/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    # /home/
    url(r'^contact/$', view=views.ContactView.as_view(), name='home.contact'),
]

publicacion/urls.py
# publicacion/urls.py
# coding=utf-8
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', view=views.IndexView.as_view()),
    url(r'^entrada/(?P<slug>[-\w]+)/$', view=views.EntradaDetailView.as_view()),
    url(r'^crear/', view=views.CrearPost.as_view()),

]

truekerosites/urls.py
from django.shortcuts import redirect
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.views.static import serve


admin.autodiscover()

urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^', include('publicacion.urls')),
    url(r'^publicacion/', include('publicacion.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publicacion/models.py
from __future__ import unicode_literals

from django.db import models
from django.template.defaultfilters import slugify
from gdstorage.storage import GoogleDriveStorage, GoogleDrivePermissionType, GoogleDrivePermissionRole, GoogleDriveFilePermission

"""
Se crean los permisos y la instancia del almacenamiento de Google Drive
para guardar las imagenes de los posts.
"""
permission =  GoogleDriveFilePermission(
   GoogleDrivePermissionRole.READER,
   GoogleDrivePermissionType.ANYONE,
 )

gd_storage = GoogleDriveStorage(permissions=(permission, ))


# Create your models here.
class Entrada(models.Model):
	"""docstring for Entrada"""
	titulo =  models.CharField(max_length=200)
	contenido = models.TextField()
	imagen = models.ImageField(upload_to="/media/",
        storage=gd_storage,
        null=True,
        blank=True,
)
	email = models.EmailField(null=False)
	number = models.CharField(max_length=15, null=None)
	slug = models.SlugField(editable=False )

	def __unicode__(self):
		return self.titulo

	#Guarda el slug automaticamente con el nombre del titulo
	def save(self, *arg, **kwargs):
		if not self.id:
			self.slug = slugify(self.titulo)
		super(Entrada, self).save(*arg, **kwargs)

publicacion/forms.py
from django import forms
from .models import Entrada

class PostForm(forms.ModelForm):

    class Meta:
        model = Entrada
        fields = ['titulo', 'contenido', 'imagen', 'email', 'number']

        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'input'}),
            'contenido': forms.Textarea()
	}

publicacion/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, PermissionDenied 
from .models import Entrada
from .forms import PostForm
# Create your views here.

class IndexView(ListView):
	"""docstring for IndexView"""
	template_name = 'publicacion.html'
	model = Entrada	

class EntradaDetailView(DetailView):
	"""docstring for EntradaDetailView"""
	template_name = 'entrada_detail.html'
	model = Entrada

class CrearPost(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """
    Esta clase crea un nuevo post.
    """
    model = Entrada
    form_class = PostForm
    template_name = 'crear_post.html'
    success_url = reverse_lazy('account_login')
    login_url = reverse_lazy('account_login')
    success_message = u'El post %(titulo)s ha sido creado exitosamente.'


class EditarPost(SuccessMessageMixin, UpdateView):

    model = Entrada
    form_class = PostForm
    template_name = 'editar_post.html'

    success_message = u'El post %(titulo)s ha sido editado.'


class EliminarPost(DeleteView):
    model = Entrada
    context_object_name = 'post'
    template_name = 'eliminar.html'

templates/base.html
  <!DOCTYPE html>
  <html>
  <html lang="es">
    <head>
      <meta charset="utf-8"/>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title>{% block title %}{% endblock %}</title>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="/static/css/materialize.min.css"  media="screen,projection"/>
      <link type="text/css" rel="stylesheet" href="/static/css/myclass.css"/>
      <link href="https://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet">
      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body>
      <div class="navbar-fixed">
       <nav>
        <div class="nav-wrapper blue">
          <a href="/publicacion/" class="brand-logo" >TrueKeros</a>
          <a href="#!" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul id="mobile-demo" class="side-nav">
              <li class="no-padding">
                <ul class="collapsible collapsible-accordion">
                  <li class="bold"><a class="center">Menú</a>
                  <li><div class="divider"></div></li>
                  <li><a href="/publicacion/" class="icon-home">¿Quieres TrueKear Algo?</a></li>
                  <li><div class="divider"></div></li>
                  {% if user.is_superuser %}
                  <li><a href="#"></a></li>
                  <li><div class="divider"></div></li>
                  <li><a href="#"></a></li>
                  <li><div class="divider"></div></li>
                  <li><a href="{% url 'account_logout' %}" class="icon-sign-out">Salir</a></li>
                  <li><div class="divider"></div></li>
                  {% elif user.is_authenticated %}
                  <li><a>{{user.first_name}}</a></li>
                  <li><div class="divider"></div></li>
                  <li><a href="/publicacion/crear">¿Tienes Algo Para TrueKear?</a></li>
                  <li><div class="divider"></div></li>
                  <li><a href="#">Mis TrueKes</a></li>
                  <li><div class="divider"></div></li>
                  <li><a href="{% url 'home.contact' %}">Contactanos</a></li>
                  <li><div class="divider"></div></li>
                  <li><a href="{% url 'account_logout' %}" class="icon-sign-out">Salir</a></li>
                  <li><div class="divider"></div></li>
                  {% else %}
                  <li><a href="{% url 'account_login' %}" class="icon-sign-in">Entrar</a></li>
                  <li><div class="divider"></div></li>
                  <li><a href="{% url 'account_signup' %}" class="icon-user">Registrarte</a></li>
                  <li><div class="divider"></div></li>
                  <li><a href="{% url 'home.contact' %}">Contactanos</a></li>
                  {% endif %}
                </ul>
              </li>
            </ul>
            <ul class="right hide-on-med-and-down">
              <li><a href="/publicacion/" class="icon-home">¿Quieres TrueKear Algo?</a></li>
              {% if user.is_superuser %}
              <li><a href="{% url 'account_logout' %}" class="icon-sign-out">Salir</a></li>
              {% elif user.is_authenticated %}
              <li><a href="#">Hola! {{ user.first_name }}</a></li>
              <li><a href="/publicacion/crear">¿Tienes Algo Para TrueKear?</a></li>
              <li><a href="{% url 'home.contact' %}">Contactanos</a></li>
              <li><a href="{% url 'account_logout' %}" class="icon-sign-out">Salir</a></li>
              {% else %}
              <li><a href="{% url 'account_login' %}" class="icon-sign-in">Entrar</a></li>
              <li><a href="{% url 'account_signup' %}" class="icon-user">Registrarte</a></li>
              <li><a href="{% url 'home.contact' %}">Contactanos</a></li>
              {% endif %}
            </ul>
         <!-- <ul class="left hide-on-med-and-down">
            <form>
              <div class="input-field" style="width: 390%">
                <input type="search" placeholder="Buscar" required>
                <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                <i class="material-icons">close</i>
              </div>
            </form>
          </ul> -->
        </div>
      </nav>
    </div>
  <div class="card-panel">
    {% block content %}{% endblock %}
  </div>
 <footer class="page-footer blue">
    <div class="footer-copyright">
      <div class="container">
      &copy; 2017 Truekeros, UTP.
      </div>
    </div>
  </footer>
      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
      <script type="text/javascript" src="/static/js/materialize.min.js"></script>
      <script>
        $(document).ready(function(){
            $(".button-collapse").sideNav();
        });
      </script>

    </body>
  </html>

templates/crear_post.html
{% extends 'base.html' %}

{% block head_title %}Crear Post{% endblock %}

{% block content %}
{% include 'post/mensajes.html' %}
<div class="contenedor-formulario">
	<h2 class="titulo-formulario">Crear Artículo</h2>
    <form action="" method="post" enctype="multipart/form-data"> {% csrf_token %}
        {% include 'form_post.html' %}
        <div class="contenedor-input">
            <input class="input" type="submit" value="Crear" />
        </div>
    </form>
</div>
{% endblock %}

templates/editar_post.html
{% extends 'base.html' %}

{% block head_title %}Editar Post{% endblock %}

{% block content %}
{% include 'post/mensajes.html' %}
    <form action="" method="post" enctype="multipart/form-data"> {% csrf_token %}
        {% include 'post/form_post.html' %}
        <div class="contenedor-input">
            <input class="input" type="submit" value="Editar" />
        </div>
    </form>
{% endblock %}

templates/eliminar_articulo.html
{% extends 'base.html' %}

{% block head_title %}Eliminar Post{% endblock %}

{% block content %}
<h1>¿Está seguro que desea eliminar el post {{post}}?</h1>
<form action="" method="post"> {% csrf_token %}
    <input type="submit" value="Eliminar" />
    <a href="{% url 'post:lista' %}">Cancelar</a>
</form>
{% endblock %}

templates/entrada_detail.html
{% extends 'base.html' %}

{% block title %}TrueKeros{% endblock title %}

{% block content %}
<div class="container">
            <div class="page-header">
                <h2><font color="blue">{{ object.titulo}}</font></h2>
            </div>
	
	<img class="responsive-img" src="{{ entrada.imagen.url }}"/>
	<p>{{ object.contenido }}</p>
	 <div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s6">
          <i class="material-icons prefix">account_circle</i>
          <input disabled  id="disabled" type="text" class="">
          <label for="disabled">{{ object.email }}</label>
        </div>
        <div class="input-field col s6">
          <i class="material-icons prefix">phone</i>
          <input disabled  id="disabled" type="text" class="">
          <label for="disabled">{{ object.number }}</label>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

templates/form_post.html
<!-- Muestra los errores en el campo titulo -->
{% if form.titulo.errors %}
<div class="contenedor-mensaje error">
    {% for error in form.titulo.errors %}
    <span>{{error}}</span>
    {% endfor %}
</div>
{% endif %}
<!-- Campo Titulo -->
<div class="contenedor-input">
	<label for="id_titulo"><b>Titulo:</b></label>
	{{form.titulo}}
</div>

<!-- Muestra los errores en el campo contenido -->
{% if form.contenido.errors %}
<div class="contenedor-mensaje error">
    {% for error in form.contenido.errors %}
    <span>{{error}}</span>
    {% endfor %}
</div>
{% endif %}
<!-- Campo contenido -->
<div class="contenedor-input">
	<label for="id_contenido"><b>Contenido:</b></label>
	{{form.contenido}}
</div>

<!-- Muestra los errores en el campo imagen -->
{% if form.imagen.errors %}
<div class="contenedor-mensaje error">
    {% for error in form.imagen.errors %}
    <span>{{error}}</span>
    {% endfor %}
</div>
{% endif %}
<!-- Campo Imagen-->
<div class="contenedor-input">
	<label for="id_imagen" class="icon-imagen"><b>Imagen:</b></label>
    <div>{{form.imagen}}</div>
</div>

<div class="contenedor-input">
    <label for="id_email"><b>Email:</b></label>
    <div>{{form.email}}</div>
</div>

<div class="contenedor-input">
    <label for="id_number"><b>WhatApp:</b></label>
    <div>{{form.number}}</div>
</div>

templates/publicacion.html
{% extends 'base.html' %}

{% block title %}TrueKeros{% endblock title %}

{% block content %}

<div class="container">

  <!-- Example row of columns -->
  <div class="row">
  {% for entrada in object_list %}
    <div class="col m4">
      <div class="card ">
        <div class="card-image waves-effect waves-block waves-light">
          <img class="activator" src="{{entrada.imagen.url}}">
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4">{{ entrada.titulo }}<i class="material-icons right">more_vert</i></span>
          <p><a href="/publicacion/entrada/{{entrada.slug}}/">Ver Trueke</a></p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4">{{ entrada.titulo }}<i class="material-icons right">close</i></span>
          <p>{{ entrada.contenido }}</p>
        </div>
      </div>
    </div>
  {% endfor %}
  </div>
  {% if user.is_authenticated %}
  <div class="fixed-action-btn horizontal click-to-toggle">
    <a class="btn-floating btn-large blue">
      <i class="material-icons">menu</i>
    </a>
    <ul>
      <li><a href="#" class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
      <li><a href="#" class="btn-floating green"><i class="material-icons">publish</i></a></li>
      <li><a href="#" class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
    </ul>
  </div>
  {% elif user.is_anonymous %}
    <div class="container">
    <div class="row">
      <div class="col m6"><a href="{% url 'account_signup' %}" class="btn btn-primary blue"> Registrate&raquo;</a></div>
      <div class="col m6"><a href="{% url 'account_login' %}" class="btn btn-primary"> TrueKea&raquo;</a></div>
    </div>
  </div>
	{% endif %}
{% endblock content %}